### ISSUE TITLE
Grid Power export shown as negative

### ISSUE THREAD

**Issue by Azimuth0r** [catsmanac/home_assistant_custom_envoy#3]
In v0.0.19 you separated out the import and export energy meter entities rather than showing negative values on one entity, did you know that the power entity is still combined for both flow directions? is there a plan to separate that out as well?

**Comment by catsmanac** [comment]
Hi @Azimuth0r, sorry for the late reply, most issues are reported in the [master repository](https://github.com/briancmpbll/home_assistant_custom_envoy/issues) as this is test environment and I kind of missed this one.

Yes power is reported negative by the Envoy, while Energy is reported split. Power can be split by the integration, but since a new HA core version is now available I plan to propose improvements over there rather then here unless users really have an interest and issues with using the new core one.

You can do this also in HA itself by a simple template and 2 new entities, copying positive values in one and negative values in another. Plenty examples available and if you want I can find one for you.

**Comment by Azimuth0r** [comment]
Thanks for your info. When I tried the Core integration it was missing a lot of things, from memory there were no combined power or energy entities. has there been significant development over the past 2 months?

**Comment by catsmanac** [comment]
No not really. The battery support is more elaborated as the @briancmpbll [integration](https://github.com/briancmpbll/home_assistant_custom_envoy/releases).

HA Core is now 2 step. It uses [pyenphase ](https://github.com/pyenphase/pyenphase)to get data from the Envoy. In what is visible in HA is implemented in the HA Core Enphase Envoy integration. Both are supported by the same persons.

I've created a PR in pyenphase to [add multiphase support](https://github.com/pyenphase/pyenphase/pull/108). The PR is now in review but then will need a PR in Home assistant to provide data in entities as well. I also migrated the net consumption and production (grid im- / export) logic from [version 0.0.19](https://github.com/briancmpbll/home_assistant_custom_envoy/releases/tag/v0.0.19) to  [pyenphase](https://github.com/pyenphase/pyenphase/issues/69). Now waiting for the multiphase pr to be completed and then issue the grid one. But again, it will require then a HA issue requesting these function and change there. 

So it will take some time for features to migrate into core. Best thing is probably to create [HA issues for Enphase_envoy](https://github.com/home-assistant/core/labels/integration%3A%20enphase_envoy) integration asking for the functionality you are after.
